### ISSUE TITLE
Petite Chez 8.4: Exception in sort: ((_.0 . closure)) is not a procedure

### ISSUE THREAD

**Issue by Intensity** [webyrd/quines#4]
Hi,

I'm getting the following on the latest Debian with the 64-bit threaded Petite Chez Scheme installed.  I'm wondering what might be going on.  Should I be using a different Scheme implementation?  An older one?  Does this "quines" repository support other Scheme implementations?  Is there a newer repository that is able to do a superset of this quines demonstration?  Any help would be appreciated.

user@localhost:~/src/quines$ ~/bin/petite
Petite Chez Scheme Version 8.4
Copyright (c) 1985-2011 Cadence Research Systems

> (load "q.scm")
Testing "4 thrines"
Exception in sort: ((_.0 . closure)) is not a procedure
Type (debug) to enter the debugger.
> (debug)
debug> help
Invalid command.  Type ? for options.
debug> ?
Type i  to inspect the raise continuation (if available)
     s  to display the condition
     c  to inspect the condition
     e  or eof to exit the debugger, retaining error continuation
     q  to exit the debugger, discarding error continuation
debug> s
  Exception in sort: ((_.0 . closure)) is not a procedure
debug> c
#<compound condition>                                             : 

   fields .............. inspect fields
   name ................ inspect record name
   rtd ................. inspect record-type descriptor
   ref(r) .............. inspect named or nth element
   set! ................ set named element, if assignable
   show(s) ............. show contents of record
   ?? .................. display more options

#<compound condition>                                             : 

debug> 
>

**Comment by webyrd** [comment]
Hi!  Thanks for pointing out the error.  There was an incorrect call to 'sort' in the reifier, which I've fixed.  I've tested the code under Petite--seems to work fine now!
